### ISSUE TITLE
More details about frequency of each size of CU that predicted by PNNS

### ISSUE THREAD

**Issue by Zhong-gy** [thierrydumas/context_adaptive_neural_network_based_prediction#2]
Congratulations on your remarkable work!
In hevc, one CTU will be splited according to quadtree and the possible size of CU is 4*4 to 64*64. Do you have any details about frequency of each size of CU that predicted by PNNS and the percentage of the area occupied in the whole picture?
Thank you for your work~

**Comment by thierrydumas** [comment]
In "README.md", the section "Visualizations" has been added. I explains how to run a script that provides visualizations of the percentage of area occupied by the luminance TBs predicted by PNNS in a whole luminance channel.

Thank you for your request.
