### ISSUE TITLE
download test set error

### ISSUE THREAD

**Issue by zhaorifa666** [thierrydumas/context_adaptive_neural_network_based_prediction#4]
When I try to run creating_kodak.py, raise error "http.client.RemoteDisconnected: Remote end closed connection without response".The reason for the error maybe that the website has set up the anti-crawl mechanism, you may need to add some headers. Moreover,when I try to run "creating_bsds.py /path/to/dir_1 --path_to_directory_tar=/path/to/dir_0 ", raise error " urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>", maybe the file is too large.  Can you help me fix these mistakes? Thank you very much!

**Comment by zhaorifa666** [comment]
I have solved it , thank you!

**Comment by thierrydumas** [comment]
Pleased to know that you solved the issue. What caused the issues during the downloads? I ran `creating_kodak.py` and `creating_bsds.py` this morning, and no exception was raised.
