### ISSUE TITLE
the pretrained models

### ISSUE THREAD

**Issue by zhaorifa666** [thierrydumas/context_adaptive_neural_network_based_prediction#5]
Can you share me the pretrained models of the neural networks for predicting blocks of size 64x64?

**Comment by thierrydumas** [comment]
I can share them. However, the model of the neural network predicting blocks of size 64x64 exceeds the maximum allowed size for a GitHub repository file. Please, send me an email at <dumas--thierry@hotmail.fr> requesting this model. I will send it to you.
